import {describe,expect,it} from "vitest";
import {newProject,newTask,newWorkspace,type AppState} from "./store";
import {coalesceActivity,deriveActivityEvents,type ActivityEvent} from "./activity";

function state(){const task={...newTask(),id:"task",title:"Draft launch"},project={...newProject("Launch"),id:"project",tasks:[task]},workspace={...newWorkspace("Product"),id:"workspace",projects:[project]};return{workspaces:[workspace],activeWorkspaceId:workspace.id} satisfies AppState;}
function next(previous:AppState,update:(workspace:AppState["workspaces"][number])=>AppState["workspaces"][number]):AppState{return{...previous,workspaces:[update(previous.workspaces[0])]};}

describe("activity derivation",()=>{
 it("records selective project and task field changes",()=>{const before=state(),workspace=before.workspaces[0],project=workspace.projects[0],task=project.tasks[0];const after=next(before,w=>({...w,projects:[{...project,title:"Launch v2",description:"private project context",tasks:[{...task,risk:"high",description:"private task context"}]}]}));const events=deriveActivityEvents(before,after,1000);expect(events.map(item=>item.action)).toEqual(["project.updated","task.updated"]);expect(events[0].changes).toContainEqual({field:"title",before:"Launch",after:"Launch v2"});expect(events[0].changes).toContainEqual({field:"description"});expect(JSON.stringify(events)).not.toContain("private project context");expect(JSON.stringify(events)).not.toContain("private task context");});
 it("records status, notes, and organization changes",()=>{const before=state(),workspace=before.workspaces[0],project=workspace.projects[0],first=project.tasks[0],second={...newTask(),id:"second",title:"Review"};const withSecond=next(before,w=>({...w,projects:[{...project,tasks:[first,second]}]}));const changed=next(withSecond,w=>({...w,categories:[...w.categories,{id:"custom",label:"Custom",glyph:"·",groupId:"general"}],projects:[{...project,tasks:[{...second,stage:"active"},{...first,notes:[{id:"note",text:"do not store me",createdAt:1}]}]}]}));const events=deriveActivityEvents(withSecond,changed,2000);expect(events.some(item=>item.action==="task.stage")).toBe(true);expect(events.some(item=>item.action==="note.added")).toBe(true);expect(events.some(item=>item.action==="category.created")).toBe(true);expect(JSON.stringify(events)).not.toContain("do not store me");});
 it("records task assignment changes",()=>{const before=state(),project=before.workspaces[0].projects[0],task=project.tasks[0],after=next(before,w=>({...w,projects:[{...project,tasks:[{...task,assignee:{userId:"github:1",login:"octocat",name:"Mona",avatarUrl:""}}]}]}));const event=deriveActivityEvents(before,after).find(item=>item.action==="task.updated");expect(event?.changes).toContainEqual({field:"assignee",before:"",after:"octocat"});});
 it("records reordering within a stage",()=>{const before=state(),project=before.workspaces[0].projects[0],second={...newTask(),id:"second",title:"Review"},withSecond=next(before,w=>({...w,projects:[{...project,tasks:[project.tasks[0],second]}]})),reordered=next(withSecond,w=>({...w,projects:[{...project,tasks:[second,project.tasks[0]]}]}));expect(deriveActivityEvents(withSecond,reordered).filter(item=>item.action==="task.reordered")).toHaveLength(2);});
 it("retains snapshots for deletions without cascading task events",()=>{const before=state();const after=next(before,w=>({...w,projects:[]}));const events=deriveActivityEvents(before,after);expect(events).toHaveLength(1);expect(events[0]).toMatchObject({action:"project.deleted",entityTitle:"Launch",deleted:true,projectId:"project"});expect(events[0].summary).toContain("1 task");});
 it("ignores navigation-only state changes",()=>{const before=state(),after={...before,workspaces:[{...before.workspaces[0],activeProjectId:"project"}]};expect(deriveActivityEvents(before,after)).toEqual([]);});
});

describe("activity coalescing",()=>{it("merges a burst while retaining the first before and final after",()=>{const base:ActivityEvent={id:"new",workspaceId:"w",projectId:"p",entityType:"task",entityId:"t",entityTitle:"Final",family:"updates",action:"task.updated",summary:"Updated Final",changes:[{field:"title",before:"Middle",after:"Final"}],occurredAt:2000,coalesceKey:"w:t:content"};const older={...base,id:"old",entityTitle:"Middle",changes:[{field:"title",before:"First",after:"Middle"}],occurredAt:1000};expect(coalesceActivity([base,older])).toMatchObject([{id:"new",changes:[{field:"title",before:"First",after:"Final"}]}]);});});
