import type{Project}from"../types";import{uid}from"../types";import{normalizeWorkspace,type Categories,type Workspace}from"./store";
export function slugifyName(name:string){return name.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"project"}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
export function projectToJson(project:Project,categories:Categories){return JSON.stringify({kind:"chisel-project",version:2,exportedAt:new Date().toISOString(),categories,project},null,2)}
export function exportProject(project:Project,categories:Categories){download(`${slugifyName(project.title)}.json`,projectToJson(project,categories))}
export interface WorkspaceExportDocument{kind:"chisel-workspace";version:5;exportedAt:string;workspace:Workspace}
export function workspaceToJson(workspace:Workspace){return JSON.stringify({kind:"chisel-workspace",version:5,exportedAt:new Date().toISOString(),workspace} satisfies WorkspaceExportDocument,null,2)}
export function exportWorkspace(workspace:Workspace){download(`${slugifyName(workspace.name)}-workspace.json`,workspaceToJson(workspace))}
export function isWorkspaceExport(text:string){try{const v=JSON.parse(text);return v?.kind==="chisel-workspace"}catch{return false}}
export function parseWorkspaceJson(text:string):{workspace?:Workspace;error?:string}{try{const v=JSON.parse(text);if(v?.kind!=="chisel-workspace")return{error:"This is not a Chisel workspace export."};if(v.version!==5)return{error:"This legacy workspace format is not supported. Export it from the current app first."};const workspace=normalizeWorkspace(v.workspace);return workspace?{workspace}:{error:"The workspace contains invalid project or task data."}}catch(e){return{error:`Not valid JSON — ${e instanceof Error?e.message:"could not parse file"}`}}}
export function copyWorkspaceForImport(source:Workspace):Workspace{const projects=source.projects.map(p=>({...p,id:uid(),notes:p.notes.map(n=>({...n,id:uid()})),tasks:p.tasks.map(t=>({...t,id:uid(),notes:t.notes.map(n=>({...n,id:uid()}))}))}));return{...source,id:uid(),name:`${source.name} copy`,createdAt:Date.now(),projects,activeProjectId:null,categories:source.categories.map(c=>({...c})),categoryGroups:source.categoryGroups.map(g=>({...g})),skills:source.skills.map(s=>({...s,id:uid()}))}}
