import {useEffect,useRef,useState} from "react";
import type {BaseItem,CategoryDef,CategoryGroup,ItemConfig,Note,Stage,Task} from "../types";
import {EFFORTS,EFFORT_LABELS,RISKS,RISK_LABELS} from "../types";
import {timeAgo} from "./ui";
interface Props {item:BaseItem|Task;categories?:CategoryDef[];categoryGroups?:CategoryGroup[];config:ItemConfig;taskCount?:number;creating?:boolean;onCreate?:()=>void;onClose:()=>void;onUpdate:(patch:Partial<Omit<Task,"id"|"notes">>)=>void;onAddNote:(text:string)=>void;onDeleteNote:(id:string)=>void;onEditNote:(id:string,text:string)=>void;onToggleNoteBlock:(id:string)=>void;onToggleNoteResolved:(id:string)=>void;onDelete:()=>void;}
export function Drawer({item,categories=[],categoryGroups=[],config,taskCount,creating=false,onCreate,onClose,onUpdate,onAddNote,onDeleteNote,onEditNote,onToggleNoteBlock,onToggleNoteResolved,onDelete}:Props){
 const[draft,setDraft]=useState("");const[confirm,setConfirm]=useState(false);const title=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{setConfirm(false);if(!item.title)title.current?.focus()},[item.id,item.title]);
 const addNote=()=>{const text=draft.trim();if(text){onAddNote(text);setDraft("")}};
 return <div className="drawer-veil" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer">
  <div className="drawer-top"><select className="stage-select" value={item.stage} onChange={e=>onUpdate({stage:e.target.value as Stage})}>{config.stages.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><button className="icon-btn" onClick={onClose} aria-label="Close">✕</button></div>
  <textarea ref={title} className="drawer-title" value={item.title} rows={1} placeholder={`Untitled ${config.itemNoun}`} onChange={e=>onUpdate({title:e.target.value})}/>
  <div className="drawer-grid"><label className="field"><span className="field-label">Priority</span><div className="seg">{RISKS.map(r=><button key={r} className={`seg-btn seg-${r}${item.risk===r?" active":""}`} onClick={()=>onUpdate({risk:r})}>{RISK_LABELS[r]}</button>)}</div></label><label className="field"><span className="field-label">Effort</span><div className="seg">{EFFORTS.map(e=><button key={e} className={`seg-btn seg-${e}${item.effort===e?" active":""}`} onClick={()=>onUpdate({effort:e})}>{EFFORT_LABELS[e]}</button>)}</div></label>{config.kind==="task"&&"category" in item&&<label className="field field-wide"><span className="field-label">Category</span><select className="input" value={item.category} onChange={e=>onUpdate({category:e.target.value})}>{categoryGroups.map(g=><optgroup key={g.id} label={g.label}>{categories.filter(c=>c.groupId===g.id).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</optgroup>)}</select></label>}</div>
  <label className="field"><span className="field-label">{config.descriptionLabel}</span><textarea className="input drawer-desc" rows={5} placeholder={config.descriptionPlaceholder} value={item.description} onChange={e=>onUpdate({description:e.target.value})}/></label>
  <ListEditor values={item.tags} onChange={tags=>onUpdate({tags})}/>
  {taskCount!==undefined&&<div className="field"><span className="field-label">Tasks</span><div className="relation-empty">{taskCount} task{taskCount===1?"":"s"} in this project</div></div>}
  <div className="field"><span className="field-label">Notes</span><div className="notes">{item.notes.length===0&&<div className="notes-empty">No notes yet.</div>}{item.notes.map(n=><NoteRow key={n.id} note={n} onEdit={text=>onEditNote(n.id,text)} onDelete={()=>onDeleteNote(n.id)} onBlock={()=>onToggleNoteBlock(n.id)} onResolve={()=>onToggleNoteResolved(n.id)}/>)}</div><div className="note-composer"><textarea className="input" rows={2} placeholder="Add a note…" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="btn btn-ghost btn-sm" onClick={addNote}>Add note</button></div></div>
  <div className="drawer-foot">{creating?<><span className="drawer-timestamps">This project has not been saved yet.</span><span className="delete-confirm"><button className="btn btn-ghost btn-sm" onClick={onClose}>Cancel</button><button className="btn btn-primary btn-sm" onClick={onCreate} disabled={!item.title.trim()}>Create Project</button></span></>:<><span className="drawer-timestamps">created {timeAgo(item.createdAt)} · updated {timeAgo(item.updatedAt)}</span>{confirm?<span className="delete-confirm">{taskCount?`Delete project and ${taskCount} tasks?`:"Delete for good?"}<button className="btn btn-danger btn-sm" onClick={onDelete}>Delete</button><button className="btn btn-ghost btn-sm" onClick={()=>setConfirm(false)}>Keep</button></span>:<button className="btn btn-ghost btn-sm btn-quiet-danger" onClick={()=>setConfirm(true)}>Delete {config.itemNoun}</button>}</>}</div>
 </aside></div>;
}
function ListEditor({values,onChange}:{values:string[];onChange:(v:string[])=>void}){const[draft,setDraft]=useState("");return <div className="field"><span className="field-label">Tags</span><div className="list-editor">{values.map(v=><span className="list-item" key={v}>{v}<button className="list-remove" onClick={()=>onChange(values.filter(x=>x!==v))}>✕</button></span>)}<input className="list-input" placeholder="add tag — press Enter" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&draft.trim()){e.preventDefault();onChange([...values,draft.trim().replace(/\s+/g,"-")]);setDraft("")}}}/></div></div>}
function NoteRow({note,onEdit,onDelete,onBlock,onResolve}:{note:Note;onEdit:(t:string)=>void;onDelete:()=>void;onBlock:()=>void;onResolve:()=>void}){return <div className={`note${note.blocked?" note-blocked":note.resolved?" note-resolved":""}`}><div className="note-text" onDoubleClick={()=>{const text=prompt("Edit note",note.text);if(text?.trim())onEdit(text.trim())}}>{note.text}</div><div className="note-foot"><span>{timeAgo(note.createdAt)}</span><button className="note-menu-btn" onClick={onBlock}>{note.blocked?"Unblock":"Block"}</button><button className="note-menu-btn" onClick={onResolve}>{note.resolved?"Reopen":"Resolve"}</button><button className="note-menu-btn" onClick={onDelete}>Remove</button></div></div>}
