import {useEffect,useRef,useState} from "react";
import type {BaseItem,CategoryDef,CategoryGroup,ItemConfig,Note,Stage,Task,TaskAssignee} from "../types";
import {EFFORTS,EFFORT_LABELS,RISKS,RISK_LABELS} from "../types";
import {tagSuggestions} from "../lib/tagSuggestions";
import {timeAgo} from "./ui";
interface Props {item:BaseItem|Task;categories?:CategoryDef[];categoryGroups?:CategoryGroup[];assignees?:TaskAssignee[];config:ItemConfig;taskCount?:number;creating?:boolean;deletable?:boolean;onCreate?:()=>void;onCreateTask?:()=>void;onClose:()=>void;onUpdate:(patch:Partial<Omit<Task,"id"|"notes">>)=>void;onAddNote:(text:string)=>void;onDeleteNote:(id:string)=>void;onEditNote:(id:string,text:string)=>void;onToggleNoteBlock:(id:string)=>void;onToggleNoteResolved:(id:string)=>void;onDelete:()=>void;}
export function Drawer({item,categories=[],categoryGroups=[],assignees=[],config,taskCount,creating=false,deletable=true,onCreate,onCreateTask,onClose,onUpdate,onAddNote,onDeleteNote,onEditNote,onToggleNoteBlock,onToggleNoteResolved,onDelete}:Props){
 const[draft,setDraft]=useState("");const[confirm,setConfirm]=useState(false);const title=useRef<HTMLInputElement>(null);
 useEffect(()=>{setConfirm(false);if(!item.title)title.current?.focus()},[item.id,item.title]);
 const addNote=()=>{const text=draft.trim();if(text){onAddNote(text);setDraft("")}};
 return <div className="drawer-veil" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer">
  <div className="drawer-top"><select className="stage-select" value={item.stage} onChange={e=>onUpdate({stage:e.target.value as Stage})}>{config.stages.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><button className="icon-btn" onClick={onClose} aria-label="Close">✕</button></div>
  <input ref={title} className="drawer-title" type="text" value={item.title} placeholder={`Untitled ${config.itemNoun}`} onChange={e=>onUpdate({title:e.target.value})} onKeyDown={e=>{if(e.key==="Enter")e.preventDefault()}}/>
  <div className="drawer-grid"><label className="field"><span className="field-label">Priority</span><div className="seg">{RISKS.map(r=><button key={r} className={`seg-btn seg-${r}${item.risk===r?" active":""}`} onClick={()=>onUpdate({risk:r})}>{RISK_LABELS[r]}</button>)}</div></label><label className="field"><span className="field-label">Effort</span><div className="seg">{EFFORTS.map(e=><button key={e} className={`seg-btn seg-${e}${item.effort===e?" active":""}`} onClick={()=>onUpdate({effort:e})}>{EFFORT_LABELS[e]}</button>)}</div></label>{config.kind==="task"&&"category" in item&&<><label className="field"><span className="field-label">Category</span><select className="input" value={item.category} onChange={e=>onUpdate({category:e.target.value})}>{categoryGroups.map(g=><optgroup key={g.id} label={g.label}>{categories.filter(c=>c.groupId===g.id).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</optgroup>)}</select></label><label className="field"><span className="field-label">Assignee</span><div className="assignee-field">{item.assignee&&<AssigneeAvatar assignee={item.assignee}/>}<select className="input" value={item.assignee?.userId??""} onChange={e=>onUpdate({assignee:assignees.find(person=>person.userId===e.target.value)??null})}><option value="">Unassigned</option>{item.assignee&&!assignees.some(person=>person.userId===item.assignee?.userId)&&<option value={item.assignee.userId}>{item.assignee.name||`@${item.assignee.login}`}</option>}{assignees.map(person=><option key={person.userId} value={person.userId}>{person.name||`@${person.login}`}</option>)}</select></div></label></>}</div>
  <label className="field"><span className="field-label">{config.descriptionLabel}</span><textarea className="input drawer-desc" rows={5} placeholder={config.descriptionPlaceholder} value={item.description} onChange={e=>onUpdate({description:e.target.value})}/></label>
  <ListEditor values={item.tags} suggestions={config.kind==="task"&&"category" in item?tagSuggestions(item.category,categories):[]} onChange={tags=>onUpdate({tags})}/>
  <div className="field"><span className="field-label">Notes</span>{item.notes.length>0&&<div className="notes">{item.notes.map(n=><NoteRow key={n.id} note={n} onEdit={text=>onEditNote(n.id,text)} onDelete={()=>onDeleteNote(n.id)} onBlock={()=>onToggleNoteBlock(n.id)} onResolve={()=>onToggleNoteResolved(n.id)}/>)}</div>}<div className="note-composer"><textarea className="input" rows={2} placeholder="Add a note…" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="btn btn-ghost btn-sm" onClick={addNote}>Add note</button></div></div>
  <div className="drawer-foot">{creating?<><span className="drawer-timestamps">This {config.itemNoun} has not been saved yet.</span><span className="delete-confirm"><button className="btn btn-ghost btn-sm" onClick={onClose}>Cancel</button><button className="btn btn-primary btn-sm" onClick={onCreate} disabled={!item.title.trim()}>Create {config.label}</button></span></>:<><span className="drawer-timestamps">created {timeAgo(item.createdAt)} · updated {timeAgo(item.updatedAt)}</span><span className="drawer-actions">{onCreateTask&&!confirm&&<button className="btn btn-primary btn-sm" onClick={onCreateTask} aria-keyshortcuts="C" title="Create Task (C)">Create Task <kbd className="drawer-shortcut" aria-hidden="true">C</kbd></button>}{deletable&&(confirm?<span className="delete-confirm">{taskCount?`Delete project and ${taskCount} tasks?`:"Delete for good?"}<button className="btn btn-danger btn-sm" onClick={onDelete}>Delete</button><button className="btn btn-ghost btn-sm" onClick={()=>setConfirm(false)}>Keep</button></span>:<button className="btn btn-ghost btn-sm btn-quiet-danger" onClick={()=>setConfirm(true)}>Delete {config.itemNoun}</button>)}</span></>}</div>
 </aside></div>;
}
function AssigneeAvatar({assignee}:{assignee:TaskAssignee}){const label=assignee.name||assignee.login;return assignee.avatarUrl?<img className="assignee-avatar" src={assignee.avatarUrl} alt=""/>:<span className="assignee-avatar assignee-avatar-fallback" aria-hidden="true">{label.slice(0,1).toUpperCase()}</span>}
function ListEditor({values,suggestions,onChange}:{values:string[];suggestions:string[];onChange:(v:string[])=>void}){const[draft,setDraft]=useState("");const available=suggestions.filter(s=>!values.some(v=>v.toLowerCase()===s.toLowerCase()));const add=(tag:string)=>{const normalized=tag.trim().replace(/\s+/g,"-");if(normalized&&!values.some(v=>v.toLowerCase()===normalized.toLowerCase()))onChange([...values,normalized])};return <div className="field"><span className="field-label">Tags</span><div className="list-editor">{values.map(v=><span className="list-item" key={v}>{v}<button className="list-remove" onClick={()=>onChange(values.filter(x=>x!==v))}>✕</button></span>)}<input className="list-input" placeholder="add tag — press Enter" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&draft.trim()){e.preventDefault();add(draft);setDraft("")}}}/>{available.map(tag=><button type="button" className="tag-suggestion" aria-label={`Add suggested tag ${tag}`} key={tag} onClick={()=>add(tag)}>+ {tag}</button>)}</div></div>}
function NoteRow({note,onEdit,onDelete,onBlock,onResolve}:{note:Note;onEdit:(t:string)=>void;onDelete:()=>void;onBlock:()=>void;onResolve:()=>void}){
 const[menuOpen,setMenuOpen]=useState(false);const menuRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!menuOpen)return;const close=(event:MouseEvent)=>{if(!menuRef.current?.contains(event.target as Node))setMenuOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setMenuOpen(false)};window.addEventListener("mousedown",close);window.addEventListener("keydown",escape);return()=>{window.removeEventListener("mousedown",close);window.removeEventListener("keydown",escape)}},[menuOpen]);
 const run=(action:()=>void)=>{action();setMenuOpen(false)};
 return <div className={`note${note.blocked?" note-blocked":note.resolved?" note-resolved":""}`}><div className="note-text" onDoubleClick={()=>{const text=prompt("Edit note",note.text);if(text?.trim())onEdit(text.trim())}}>{note.text}</div><div className="note-foot"><span>{timeAgo(note.createdAt)}</span>{note.blocked&&<span className="note-blocked-tag">Blocked</span>}{note.resolved&&<span className="note-resolved-tag">Resolved</span>}<div className="note-menu" ref={menuRef}><button className="note-menu-btn" aria-label="Note actions" aria-haspopup="menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(open=>!open)}>⋯</button>{menuOpen&&<div className="note-menu-pop" role="menu"><button className="note-menu-item" role="menuitem" onClick={()=>run(onBlock)}>{note.blocked?"Unblock":"Block"}</button><button className="note-menu-item resolve" role="menuitem" onClick={()=>run(onResolve)}>{note.resolved?"Reopen":"Resolve"}</button><button className="note-menu-item danger" role="menuitem" onClick={()=>run(onDelete)}>Remove</button></div>}</div></div></div>
}
