import {useEffect,useId,useRef,useState} from "react";
import {clearCachedTaskReminder,deleteTaskReminder,fetchTaskReminder,getCachedTaskReminder,saveTaskReminder,setCachedTaskReminder} from "../lib/reminderApi";
import type {TaskReminder} from "../lib/reminders";

interface Props{workspaceId:string;projectId:string;taskId:string;completed:boolean;onFeedback:(text:string,kind?:"success"|"info"|"error")=>void}
const localValue=(iso:string)=>{const date=new Date(iso),offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};

export function ReminderEditor({workspaceId,projectId,taskId,completed,onFeedback}:Props){
 const ref={workspaceId,projectId,taskId},initial=getCachedTaskReminder(ref),inputId=useId(),requestVersion=useRef(0);const[reminder,setReminder]=useState<TaskReminder|null>(initial??null),[value,setValue]=useState(initial?localValue(initial.remindAt):""),[loading,setLoading]=useState(initial===undefined),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;const request=++requestVersion.current;setError(null);if(completed){clearCachedTaskReminder({workspaceId,projectId,taskId});setReminder(null);setValue("");setLoading(false);return()=>{cancelled=true}}const cached=getCachedTaskReminder({workspaceId,projectId,taskId});setReminder(cached??null);setValue(cached?localValue(cached.remindAt):"");setLoading(cached===undefined);void fetchTaskReminder({workspaceId,projectId,taskId}).then(item=>{if(cancelled||request!==requestVersion.current)return;setReminder(item);setValue(item?localValue(item.remindAt):"");if(item)window.dispatchEvent(new CustomEvent("chisel:reminder-saved",{detail:item.remindAt}))}).catch(reason=>{if(!cancelled&&request===requestVersion.current)setError(reason instanceof Error?reason.message:"Could not load the reminder.")}).finally(()=>{if(!cancelled&&request===requestVersion.current)setLoading(false)});return()=>{cancelled=true}},[workspaceId,projectId,taskId,completed]);
 const save=async()=>{const timestamp=Date.parse(value);if(!value||!Number.isFinite(timestamp)||timestamp<=Date.now()){setError("Choose a future date and time.");return}requestVersion.current++;setLoading(false);setSaving(true);setError(null);const previous=reminder,now=new Date().toISOString(),remindAt=new Date(timestamp).toISOString(),optimistic:TaskReminder={id:previous?.id??`pending:${taskId}`,workspaceId,projectId,taskId,remindAt,createdAt:previous?.createdAt??now,updatedAt:now};setReminder(optimistic);setValue(localValue(remindAt));setCachedTaskReminder(ref,optimistic);window.dispatchEvent(new CustomEvent("chisel:reminder-saved",{detail:remindAt}));onFeedback(previous?"Reminder updated":"Reminder set","success");try{const item=await saveTaskReminder(ref,remindAt);setReminder(item);setValue(localValue(item.remindAt))}catch(reason){if(previous){setReminder(previous);setValue(localValue(previous.remindAt));setCachedTaskReminder(ref,previous)}else{setReminder(null);clearCachedTaskReminder(ref)}const message=reason instanceof Error?reason.message:"Could not save the reminder.";setError(message);onFeedback("Reminder could not be saved","error")}finally{setSaving(false)}};
 const remove=async()=>{requestVersion.current++;setLoading(false);setSaving(true);setError(null);try{await deleteTaskReminder(ref);setReminder(null);setValue("");onFeedback("Reminder removed","info")}catch(reason){setError(reason instanceof Error?reason.message:"Could not remove the reminder.")}finally{setSaving(false)}};
 const min=localValue(new Date(Date.now()+60000).toISOString());
 return <div className="field reminder-field"><div className="reminder-label-row"><label className="field-label" htmlFor={inputId}>Reminder</label></div>{completed?<p className="reminder-help">Completed tasks cannot have reminders.</p>:<><div className="reminder-controls"><input id={inputId} className="input" type="datetime-local" step="60" min={min} value={value} onChange={event=>{requestVersion.current++;setLoading(false);setValue(event.target.value)}}/><button className="btn btn-primary btn-sm" disabled={saving||!value} onClick={()=>void save()}>{reminder?"Update":"Set reminder"}</button>{reminder&&<button className="btn btn-ghost btn-sm" disabled={saving} onClick={()=>void remove()}>Remove</button>}</div>{loading&&<p className="reminder-help">Checking for an existing reminder…</p>}</>}{error&&<p className="reminder-error" role="alert">{error}</p>}</div>;
}
