import {useEffect,useMemo,useRef,useState} from "react";
import type {GitHubUser} from "../lib/auth";
import type {Project} from "../types";
import type {ActivityEvent,ActivityFamily,ActivityPage,ActivityProjectOption} from "../lib/activity";
import {fetchActivityPage} from "../lib/activityApi";
import {fetchGuestActivity,subscribeGuestActivity} from "../lib/guestActivity";
import {getCachedActivity,invalidateActivityCache,loadActivity,type ActivityRequest} from "../lib/activityCache";

interface Props{workspaceId:string;projects:Project[];projectId?:string|null;isGuest:boolean;user:GitHubUser;syncKey?:string|null;onOpen:(event:ActivityEvent)=>void;}
const FAMILIES:{id:ActivityFamily|null;label:string}[]=[{id:null,label:"All activity"},{id:"status",label:"Status"},{id:"updates",label:"Updates"},{id:"notes",label:"Notes"},{id:"organization",label:"Organization"}];
const FAMILY_LABELS:Record<ActivityFamily,string>={status:"Status Changed",updates:"Details Updated",notes:"Note Updated",organization:"Organization"};
const NOTE_LABELS:Record<string,string>={"note.added":"Note Added","note.deleted":"Note Removed","note.edited":"Note Edited","note.blocked":"Note Blocked","note.unblocked":"Note Unblocked","note.resolved":"Note Resolved","note.reopened":"Note Reopened"};
const EMPTY:ActivityPage={events:[],nextCursor:null,projects:[],summary:{today:0,thisWeek:0,itemsTouched:0}};
const stageLabel=(value:string)=>({queued:"To do",active:"In progress",reviewing:"Review",deployed:"Done",deferred:"On hold"}[value]??value);
const displayValue=(field:string,value?:string)=>value===undefined?"":field==="status"?stageLabel(value):value||"None";
const titleCase=(value:string)=>value.replace(/[-_]/g," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const activityLabel=(item:ActivityEvent)=>{if(item.family==="notes")return NOTE_LABELS[item.action]??FAMILY_LABELS.notes;if(item.family!=="updates")return FAMILY_LABELS[item.family];const fields=[...new Set(item.changes.map(change=>titleCase(change.field)))];return fields.length===1?`${fields[0]} Updated`:fields.length===2?`${fields[0]} & ${fields[1]} Updated`:fields.length>2?`${fields.length} Fields Updated`:FAMILY_LABELS.updates};
const dayKey=(timestamp:number)=>new Date(timestamp).toDateString();
const dayLabel=(timestamp:number)=>{const date=new Date(timestamp),today=new Date(),yesterday=new Date(Date.now()-86400000);if(date.toDateString()===today.toDateString())return"Today";if(date.toDateString()===yesterday.toDateString())return"Yesterday";return date.toLocaleDateString([], {weekday:"long",month:"long",day:"numeric",year:date.getFullYear()===today.getFullYear()?undefined:"numeric"});};

export function Timeline({workspaceId,projects,projectId=null,isGuest,user,syncKey,onOpen}:Props){
 const[family,setFamily]=useState<ActivityFamily|null>(null),[projectFilter,setProjectFilter]=useState(projectId),[query,setQuery]=useState(""),[debouncedQuery,setDebouncedQuery]=useState(""),[retryKey,setRetryKey]=useState(0);
 const forceNextLoad=useRef(false);
 const request=useMemo<ActivityRequest>(()=>({mode:isGuest?"guest":"signed",userKey:String(user.id),workspaceId,projectId:projectId??projectFilter,family,query:debouncedQuery,revision:syncKey}),[isGuest,user.id,workspaceId,projectId,projectFilter,family,debouncedQuery,syncKey]);
 const[page,setPage]=useState<ActivityPage>(()=>getCachedActivity(request)??EMPTY),[loading,setLoading]=useState(()=>!getCachedActivity(request)),[refreshing,setRefreshing]=useState(false),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState<string|null>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQuery(query),220);return()=>window.clearTimeout(timer)},[query]);
 useEffect(()=>setProjectFilter(projectId),[projectId,workspaceId]);
 useEffect(()=>{let cancelled=false;const cached=getCachedActivity(request),force=forceNextLoad.current;forceNextLoad.current=false;setPage(cached??EMPTY);setLoading(!cached);setRefreshing(Boolean(cached));setError(null);void loadActivity(request,force).then(result=>{if(!cancelled)setPage(result)}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Could not load activity.")}).finally(()=>{if(!cancelled){setLoading(false);setRefreshing(false)}});return()=>{cancelled=true}},[request,retryKey]);
 useEffect(()=>{if(!isGuest)return;let cancelled=false;const unsubscribe=subscribeGuestActivity(workspaceId,()=>{invalidateActivityCache("guest",workspaceId);setRefreshing(true);void loadActivity(request,true).then(result=>{if(!cancelled)setPage(result)}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Could not refresh activity.")}).finally(()=>{if(!cancelled)setRefreshing(false)})});return()=>{cancelled=true;unsubscribe()}},[isGuest,workspaceId,request]);
 const groups=useMemo(()=>{const result:{key:string;label:string;timestamp:number;events:ActivityEvent[]}[]=[];for(const item of page.events){const key=dayKey(item.occurredAt),last=result[result.length-1];if(last?.key===key)last.events.push(item);else result.push({key,label:dayLabel(item.occurredAt),timestamp:item.occurredAt,events:[item]});}return result},[page.events]);
 const loadMore=async()=>{if(!page.nextCursor)return;setLoadingMore(true);try{const next=isGuest?await fetchGuestActivity(workspaceId,{projectId:projectFilter,family,query:debouncedQuery,cursor:page.nextCursor}):await fetchActivityPage({workspaceId,projectId:projectFilter,family,query:debouncedQuery,cursor:page.nextCursor});setPage(current=>({...next,events:[...current.events,...next.events],projects:current.projects.length?current.projects:next.projects,summary:current.summary}));}catch(reason){setError(reason instanceof Error?reason.message:"Could not load earlier activity.");}finally{setLoadingMore(false)}};
 const projectOptions:ActivityProjectOption[]=page.projects.length?page.projects:projects.map(project=>({id:project.id,title:project.title||"Untitled project"}));
 const scopeProject=projectId?projects.find(project=>project.id===projectId):null,scopeTitle=scopeProject?.title?.trim()||"Project";
 const hasFilters=Boolean(query||family||(!projectId&&projectFilter));
 const clearFilters=()=>{setQuery("");setDebouncedQuery("");setFamily(null);if(!projectId)setProjectFilter(null)};
 const retry=()=>{forceNextLoad.current=true;setRetryKey(value=>value+1)};
 return <main className="timeline-page"><section className="timeline-shell" aria-labelledby="timeline-title" aria-busy={loading||refreshing}>
  <header className="timeline-hero"><div className="timeline-heading"><span className="front-kicker">{projectId?"Project activity":"Workspace activity"}</span><h1 id="timeline-title">{projectId?`${scopeTitle} timeline`:"Your workspace story"}</h1><p>{projectId?"A focused history of decisions, progress, and project changes.":"A chronological record of the meaningful work happening across every project."}</p></div><div className="timeline-metrics" aria-label="Activity summary"><Metric value={page.summary.today} label="Today"/><Metric value={page.summary.thisWeek} label="This week"/><Metric value={page.summary.itemsTouched} label="Items touched"/></div></header>
  <div className="timeline-controls"><div className="timeline-control-primary"><label className="timeline-search"><SearchIcon/><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search people, projects, and changes" aria-label="Search activity"/>{query&&<button type="button" onClick={()=>setQuery("")} aria-label="Clear search">×</button>}</label>{!projectId&&<label className="timeline-project-filter"><span className="sr-only">Filter by project</span><select value={projectFilter??""} onChange={event=>setProjectFilter(event.target.value||null)}><option value="">Every project</option>{projectOptions.map(option=><option key={option.id} value={option.id}>{option.title}{option.deleted?" (deleted)":""}</option>)}</select></label>}</div><div className="timeline-control-secondary"><div className="timeline-family-tabs" role="group" aria-label="Filter activity type">{FAMILIES.map(option=><button type="button" key={option.label} className={family===option.id?"active":""} aria-pressed={family===option.id} onClick={()=>setFamily(option.id)}>{option.id&&<FamilyIcon family={option.id}/>}<span>{option.label}</span></button>)}</div><div className="timeline-control-status">{refreshing&&<span className="timeline-refreshing" role="status"><span aria-hidden="true"/>Updating</span>}{hasFilters&&<button type="button" className="timeline-clear" onClick={clearFilters}>Clear filters</button>}</div></div></div>
  {error&&page.events.length>0&&<div className="timeline-refresh-error" role="status"><span>!</span><div><strong>Timeline couldn’t update</strong><small>Showing your latest cached activity.</small></div><button type="button" onClick={retry}>Try again</button></div>}
  {error&&!page.events.length&&!loading?<TimelineError message={error} onRetry={retry}/>:loading?<TimelineSkeleton/>:!page.events.length?<div className="timeline-state timeline-empty"><span aria-hidden="true">◇</span><strong>{hasFilters?"No activity found":"Your timeline starts here"}</strong><p>{hasFilters?"Nothing matches this combination of search and filters.":"New workspace and project changes will appear here. Existing history was intentionally not reconstructed."}</p>{hasFilters&&<button type="button" className="btn btn-ghost" onClick={clearFilters}>Reset all filters</button>}</div>:<div className="timeline-groups">{groups.map(group=><section className="timeline-day" key={group.key}><header><h2>{group.label}</h2><time dateTime={new Date(group.timestamp).toISOString()}>{group.events.length} {group.events.length===1?"change":"changes"}</time></header><div className="timeline-list">{group.events.map(item=><TimelineCard key={item.id} item={item} actor={user} isGuest={isGuest} showProject={!projectId} canOpen={!item.deleted&&((item.entityType==="project"&&projects.some(p=>p.id===item.entityId))||(item.entityType==="task"&&projects.some(p=>p.id===item.projectId&&p.tasks.some(t=>t.id===item.entityId))))} onOpen={onOpen}/>)}</div></section>)}{page.nextCursor&&<div className="timeline-more-wrap"><span>There’s more to the story</span><button className="btn btn-ghost timeline-more" disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?"Loading earlier activity…":"Load earlier activity"}</button></div>}</div>}
 </section></main>
}

function Metric({value,label}:{value:number;label:string}){return <div><strong>{value.toLocaleString()}</strong><span>{label}</span></div>}
function FamilyIcon({family}:{family:ActivityFamily}){return <svg className={`timeline-family-icon timeline-family-icon-${family}`} viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="6"/><path d={family==="status"?"M5 9.5 7.2 7 9 8.5 11.5 5.5":family==="updates"?"M5 11 5.6 8.1 10 3.8 12.2 6 7.9 10.4 5 11Z":family==="notes"?"M5 5.5h6M5 8h6M5 10.5h4":"M8 4v8M4 8h8"}/></svg>}
function SearchIcon(){return <svg className="timeline-search-icon" viewBox="0 0 16 16" aria-hidden="true"><circle cx="7" cy="7" r="4.5"/><path d="m10.5 10.5 3 3"/></svg>}
function TimelineSkeleton(){return <div className="timeline-skeleton" role="status"><span className="sr-only">Loading the story so far…</span>{[0,1,2].map(item=><div key={item}><span/><section><i/><i/><i/></section></div>)}</div>}
function TimelineError({message,onRetry}:{message:string;onRetry:()=>void}){return <div className="timeline-state timeline-error" role="alert"><span aria-hidden="true">!</span><strong>Activity could not be loaded</strong><p>{message}</p><button type="button" className="btn btn-ghost" onClick={onRetry}>Try again</button></div>}
function TimelineCard({item,actor,isGuest,showProject,canOpen,onOpen}:{item:ActivityEvent;actor:GitHubUser;isGuest:boolean;showProject:boolean;canOpen:boolean;onOpen:(event:ActivityEvent)=>void}){
 const date=new Date(item.occurredAt),time=date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),absolute=date.toLocaleString([],{dateStyle:"medium",timeStyle:"short"});
 const content=<><span className={`timeline-icon timeline-icon-${item.family}`}><FamilyIcon family={item.family}/></span><div className="timeline-card-body"><div className="timeline-card-labels"><span className={`timeline-family-label timeline-family-label-${item.family}`}>{activityLabel(item)}</span>{item.family!=="status"&&item.family!=="notes"&&<span>{item.entityType.replace("-"," ")}</span>}{item.deleted&&<span className="timeline-deleted">Deleted</span>}</div><h3>{item.summary}</h3><div className="timeline-card-meta">{isGuest?<span className="timeline-avatar timeline-avatar-guest">G</span>:<img className="timeline-avatar" src={actor.avatarUrl} alt=""/>}<strong>{isGuest?"Guest":actor.name||actor.login}</strong><span>at</span><time dateTime={date.toISOString()} title={absolute}>{time}</time>{showProject&&item.projectTitle&&<><span className="timeline-meta-dot">·</span><em>{item.projectTitle}</em></>}</div>{item.changes.length>0&&<div className="timeline-changes">{item.changes.map((change,index)=><span key={`${change.field}-${index}`} title={change.before!==undefined&&change.after!==undefined?`${displayValue(change.field,change.before)} → ${displayValue(change.field,change.after)}`:undefined}><b>{change.field}</b>{change.before!==undefined&&change.after!==undefined?<><del>{displayValue(change.field,change.before)}</del><i>→</i><ins>{displayValue(change.field,change.after)}</ins></>:<small>Content updated</small>}</span>)}</div>}</div></>;
 return canOpen?<button type="button" className="timeline-card timeline-card-clickable" aria-label={`Open ${item.entityType.replace("-"," ")} ${item.entityTitle}`} onClick={()=>onOpen(item)}>{content}<span className="timeline-open" aria-hidden="true">Open <b>→</b></span></button>:<article className={`timeline-card${item.deleted?" timeline-card-deleted":""}`}>{content}</article>
}
