import{useEffect,useMemo,useRef,useState}from"react";
import{Board}from"./components/Board";import{CategoryManager}from"./components/CategoryManager";import{Drawer}from"./components/Drawer";import{Header}from"./components/Header";import{SignInScreen}from"./components/SignIn";import{SkillsManager}from"./components/SkillsManager";import{ToastHost,useToasts}from"./components/Toast";import{WorkspaceImportModal}from"./components/WorkspaceImportModal";
import{boardScope,guestSession,type Session,useAuth}from"./lib/auth";import{exportWorkspace}from"./lib/export";import{NEW_SKILL_BODY,type Skill}from"./lib/skills";import{activeProject,activeWorkspace,DEFAULT_WORKSPACE_NAME,newProject,newTask,useBoard}from"./lib/store";import type{Project,Risk}from"./types";import{PROJECT_CONFIG,TASK_CONFIG,uid}from"./types";
export interface Filters{query:string;risks:Set<Risk>;blockedOnly:boolean}const EMPTY:Filters={query:"",risks:new Set(),blockedOnly:false};
export default function App(){const{session,loading,signIn,signOut}=useAuth();const[name,setName]=useState<string|null>(null);if(loading)return null;if(!session)return <SignInScreen onCreateWorkspace={n=>{setName(n);signIn(guestSession())}}/>;return <BoardApp session={session} onSignOut={signOut} initialName={name}/>}
function BoardApp({session,onSignOut,initialName}:{session:Session;onSignOut:()=>void;initialName:string|null}){const{state,dispatch,sync}=useBoard(boardScope(session),session.kind==="github"?"session":null);const workspace=activeWorkspace(state),project=activeProject(state);const[filters,setFilters]=useState<Filters>(EMPTY);const[selectedTask,setSelectedTask]=useState<string|null>(null);const[selectedProject,setSelectedProject]=useState<string|null>(null);const[projectDraft,setProjectDraft]=useState<Project|null>(null);const[categoriesOpen,setCategoriesOpen]=useState(false);const[skillsOpen,setSkillsOpen]=useState(false);const[workspaceFile,setWorkspaceFile]=useState<File|null>(null);const fileRef=useRef<HTMLInputElement>(null);const{toasts,pushToast,dismissToast}=useToasts();const initialized=useRef(false);if(initialName&&!initialized.current&&workspace.name===DEFAULT_WORKSPACE_NAME){initialized.current=true;dispatch({type:"workspace-rename",id:workspace.id,name:initialName})}
 const tasks=project?.tasks??[];const filtered=useMemo(()=>tasks.filter(t=>{const q=filters.query.trim().toLowerCase();return(!filters.blockedOnly||t.blocked)&&(!filters.risks.size||filters.risks.has(t.risk))&&(!q||[t.title,t.description,...t.tags].join(" ").toLowerCase().includes(q))}),[tasks,filters]);const task=tasks.find(t=>t.id===selectedTask)??null;const detailProject=workspace.projects.find(p=>p.id===selectedProject)??null;const reset=()=>{dispatch({type:"project-select",id:null});setSelectedTask(null);setSelectedProject(null);setFilters(EMPTY)};const noteAction=(type:any,entity:"project"|"task",projectId:string,taskId?:string,noteId?:string,text?:string)=>dispatch({type,entity,projectId,taskId,noteId,text} as any);
 const createSkill=()=>{const now=Date.now(),skill:Skill={id:uid(),name:"Untitled skill",description:"",body:NEW_SKILL_BODY,createdAt:now,updatedAt:now};dispatch({type:"skill-create",skill});return skill};const categoryCounts=Object.fromEntries(workspace.categories.map(c=>[c.id,workspace.projects.reduce((sum,p)=>sum+p.tasks.filter(t=>t.category===c.id).length,0)]));
 return <div className="app"><input ref={fileRef} hidden type="file" accept=".json" onChange={e=>{const f=e.target.files?.[0];if(f)setWorkspaceFile(f)}}/><Header items={tasks} project={project} workspaces={state.workspaces} activeWorkspaceId={state.activeWorkspaceId} filters={filters} onFilters={setFilters} onManageCategories={()=>setCategoriesOpen(true)} onManageSkills={()=>setSkillsOpen(true)} onHome={reset} user={session.user} isGuest={session.kind==="guest"} sync={sync} onSignOut={onSignOut} onWorkspaceSwitch={id=>{dispatch({type:"workspace-switch",id});reset()}} onWorkspaceCreate={name=>dispatch({type:"workspace-create",name})} onWorkspaceRename={(id,name)=>dispatch({type:"workspace-rename",id,name})} onWorkspaceDelete={id=>dispatch({type:"workspace-delete",id})}/>
 {project?<Board items={filtered} totalCount={tasks.length} categories={workspace.categories} config={TASK_CONFIG} onMove={(id,stage,beforeId)=>dispatch({type:"task-move",projectId:project.id,id,stage,beforeId})} onSelect={setSelectedTask} onAddItem={stage=>{const t=newTask(stage);dispatch({type:"task-add",projectId:project.id,task:t});setSelectedTask(t.id)}} onLoadSample={()=>{for(const title of["Define acceptance criteria","Prepare rollout","Review results"]){const t={...newTask(),title};dispatch({type:"task-add",projectId:project.id,task:t})}}}/>:<ProjectOverview projects={workspace.projects} onOpen={id=>dispatch({type:"project-select",id})} onEdit={setSelectedProject} onCreate={()=>setProjectDraft(newProject())} onImport={()=>fileRef.current?.click()} onExport={()=>exportWorkspace(workspace)}/>}
 {projectDraft&&<Drawer item={projectDraft} config={PROJECT_CONFIG} taskCount={0} creating onCreate={()=>{dispatch({type:"project-create",project:projectDraft});setProjectDraft(null);pushToast(`Project “${projectDraft.title}” created`,"success")}} onClose={()=>setProjectDraft(null)} onUpdate={patch=>setProjectDraft(current=>current?{...current,...patch,updatedAt:Date.now()}:current)} onAddNote={()=>{}} onDeleteNote={()=>{}} onEditNote={()=>{}} onToggleNoteBlock={()=>{}} onToggleNoteResolved={()=>{}} onDelete={()=>setProjectDraft(null)}/>} {detailProject&&<Drawer item={detailProject} config={PROJECT_CONFIG} taskCount={detailProject.tasks.length} onClose={()=>setSelectedProject(null)} onUpdate={patch=>dispatch({type:"project-update",id:detailProject.id,patch})} onAddNote={text=>noteAction("note-add","project",detailProject.id,undefined,undefined,text)} onDeleteNote={id=>noteAction("note-delete","project",detailProject.id,undefined,id)} onEditNote={(id,text)=>noteAction("note-edit","project",detailProject.id,undefined,id,text)} onToggleNoteBlock={id=>noteAction("note-toggle-block","project",detailProject.id,undefined,id)} onToggleNoteResolved={id=>noteAction("note-toggle-resolved","project",detailProject.id,undefined,id)} onDelete={()=>{dispatch({type:"project-delete",id:detailProject.id});setSelectedProject(null);pushToast("Project and its tasks deleted","info")}}/>}
 {task&&project&&<Drawer item={task} categories={workspace.categories} categoryGroups={workspace.categoryGroups} config={TASK_CONFIG} onClose={()=>setSelectedTask(null)} onUpdate={patch=>dispatch({type:"task-update",projectId:project.id,id:task.id,patch})} onAddNote={text=>noteAction("note-add","task",project.id,task.id,undefined,text)} onDeleteNote={id=>noteAction("note-delete","task",project.id,task.id,id)} onEditNote={(id,text)=>noteAction("note-edit","task",project.id,task.id,id,text)} onToggleNoteBlock={id=>noteAction("note-toggle-block","task",project.id,task.id,id)} onToggleNoteResolved={id=>noteAction("note-toggle-resolved","task",project.id,task.id,id)} onDelete={()=>{dispatch({type:"task-delete",projectId:project.id,id:task.id});setSelectedTask(null)}}/>}
 {workspaceFile&&<WorkspaceImportModal file={workspaceFile} onClose={()=>setWorkspaceFile(null)} onImport={w=>{dispatch({type:"workspace-import",workspace:w});setWorkspaceFile(null)}}/>}
 {categoriesOpen&&<CategoryManager categories={workspace.categories} groups={workspace.categoryGroups} counts={categoryCounts} onAdd={(label,groupId)=>dispatch({type:"category-add",label,groupId})} onRename={(id,label)=>dispatch({type:"category-rename",id,label})} onSetGlyph={(id,glyph)=>dispatch({type:"category-set-glyph",id,glyph})} onDelete={id=>dispatch({type:"category-delete",id})} onMove={(id,groupId)=>dispatch({type:"category-move",id,groupId})} onReorder={(id,direction)=>dispatch({type:"category-reorder",id,direction})} onGroupAdd={label=>dispatch({type:"category-group-add",label})} onGroupRename={(id,label)=>dispatch({type:"category-group-rename",id,label})} onGroupDelete={id=>dispatch({type:"category-group-delete",id})} onGroupReorder={(id,direction)=>dispatch({type:"category-group-reorder",id,direction})} onClose={()=>setCategoriesOpen(false)}/>} {skillsOpen&&<SkillsManager skills={workspace.skills} categories={project?workspace.categories:[]} config={project?TASK_CONFIG:PROJECT_CONFIG} onCreate={createSkill} onUpdate={(id,patch)=>dispatch({type:"skill-update",id,patch})} onDelete={id=>dispatch({type:"skill-delete",id})} onClose={()=>setSkillsOpen(false)}/>}<ToastHost toasts={toasts} onDismiss={dismissToast}/></div>}
function ProjectOverview({projects,onOpen,onEdit,onCreate,onImport,onExport}:{projects:Project[];onOpen:(id:string)=>void;onEdit:(id:string)=>void;onCreate:()=>void;onImport:()=>void;onExport:()=>void}){
 const[transferOpen,setTransferOpen]=useState(false);const transferRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!transferOpen)return;const close=(e:MouseEvent)=>{if(!transferRef.current?.contains(e.target as Node))setTransferOpen(false)};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape")setTransferOpen(false)};window.addEventListener("mousedown",close);window.addEventListener("keydown",escape);return()=>{window.removeEventListener("mousedown",close);window.removeEventListener("keydown",escape)}},[transferOpen]);
 return <main className="board-empty"><section className="front-page"><div className="front-copy">
  <div className="workspace-kicker-row"><span className="front-kicker">Workspace</span><div className="workspace-transfer" ref={transferRef}><button className={`workspace-transfer-trigger${transferOpen?" open":""}`} onClick={()=>setTransferOpen(open=>!open)} aria-label="Workspace import and export" aria-haspopup="menu" aria-expanded={transferOpen}><span aria-hidden="true">↕</span></button>{transferOpen&&<div className="workspace-transfer-menu" role="menu"><button role="menuitem" onClick={()=>{setTransferOpen(false);onImport()}}><span aria-hidden="true">⇡</span><span><strong>Import workspace</strong><small>Load a workspace JSON file</small></span></button><button role="menuitem" onClick={()=>{setTransferOpen(false);onExport()}}><span aria-hidden="true">⇣</span><span><strong>Export workspace</strong><small>Download a complete backup</small></span></button></div>}</div></div>
  <h1>Projects, without the extra layers</h1><p className="front-lede">Choose a project to open its task board, or create a new one.</p>
  <div className="front-actions"><button className="btn btn-primary" onClick={onCreate}>+ New Project</button></div>
  <div className="project-overview-grid">{projects.map(p=>{const done=p.tasks.filter(t=>t.stage==="deployed").length,pct=p.tasks.length?done/p.tasks.length*100:0;return <article className="front-value project-overview-card" key={p.id} onClick={()=>onOpen(p.id)} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onOpen(p.id)}}}>
   <button className="icon-btn project-card-menu" onClick={e=>{e.stopPropagation();onEdit(p.id)}} aria-label={`Edit ${p.title||"project"}`}>⋯</button>
   <div className="project-card-copy"><h2>{p.title||"Untitled project"}</h2><p>{p.description||"No outcome added yet."}</p></div>
   <div className="project-card-footer"><div className="project-card-progress" aria-hidden="true"><span style={{width:`${pct}%`}}/></div><span className="project-card-count" aria-label={`${done} of ${p.tasks.length} tasks done`}>{done}/{p.tasks.length}</span></div>
  </article>})}</div>
 </div></section></main>
}
